DATABASE_URL=op://Dev/AgentePQRS/DATABASE_URL
REDIS_URL=op://Dev/AgentePQRS/REDIS_URL
JWT_SECRET_KEY=op://Dev/AgentePQRS/JWT_SECRET_KEY
KAFKA_BOOTSTRAP_SERVERS=op://Dev/AgentePQRS/KAFKA_BOOTSTRAP_SERVERS
MINIO_ENDPOINT=op://Dev/AgentePQRS/MINIO_ENDPOINT
MINIO_ACCESS_KEY=op://Dev/AgentePQRS/MINIO_ACCESS_KEY
MINIO_SECRET_KEY=op://Dev/AgentePQRS/MINIO_SECRET_KEY
ANTHROPIC_API_KEY=op://Dev/AgentePQRS/ANTHROPIC_API_KEY
DEMO_GMAIL_USER=op://Dev/AgentePQRS/DEMO_GMAIL_USER
DEMO_GMAIL_PASSWORD=op://Dev/AgentePQRS/DEMO_GMAIL_PASSWORD

REDIS_PASSWORD=op://Dev/AgentePQRS/REDIS_PASSWORD
AZURE_CLIENT_SECRET=op://Dev/AgentePQRS/AZURE_CLIENT_SECRET
AZURE_TENANT_ID=op://Dev/AgentePQRS/AZURE_TENANT_ID
AZURE_CLIENT_ID=op://Dev/AgentePQRS/AZURE_CLIENT_ID
WORKER_DB_URL=op://Dev/AgentePQRS/WORKER_DB_URL
VOYAGE_API_KEY=op://Dev/AgentePQRS/VOYAGE_API_KEY

